---
    - name: provision an EC2 instance in the ca-central-1a region to join a mongodb replica set
      hosts: localhost
      connection: local
      become: yes
      become_method: sudo
      debugger: on_failed
      gather_facts: yes
      tasks:

          - name: run ipgateway stuff
            shell: node ./eni-netplan.js
            register: ipgateway_res

          - debug: var=ipgateway_res
